### ISSUE TITLE
no open2?

### ISSUE THREAD

**Issue by jaudall** [mathii/gdc#1]
Is there not a open2 function?

-bash-4.1$ python ../../script/vcf2eigenstrat.py -v BPS1206.Recali.gatk.vcf.snp.HQ -o test
[('-v', 'BPS1206.Recali.gatk.vcf.snp.HQ'), ('-o', 'test')] []
-v BPS1206.Recali.gatk.vcf.snp.HQ
-o test
found options:
{'indmap': None, 'indAsPop': False, 'ref': None, 'vcf': 'BPS1206.Recali.gatk.vcf.snp.HQ', 'out': 'test'}
Traceback (most recent call last):
  File "../../script/vcf2eigenstrat.py", line 138, in <module>
    main(options)
  File "../../script/vcf2eigenstrat.py", line 45, in main
    vcf=gdc.open2(options["vcf"])
AttributeError: 'module' object has no attribute 'open2'

**Comment by mathii** [comment]
Which python version are you using?
