### ISSUE TITLE
No module named gdc 

### ISSUE THREAD

**Issue by LimWChing** [mathii/gdc#3]
Hi, I ran the vcf2eigenstrat.py script, but I got the following error. This might sound a bit weird of me to ask, but am I supposed to clone the whole gdc to be able to run this? Is gdc a self defined module?

FYI, I am using Python 2.7.15.

Thank you.

```
Traceback (most recent call last):
  File "/home/wlim/exploring_vcf/vcf2eigenstrat.py", line 10, in <module>
    import sys, getopt, gdc, pdb
ImportError: No module named gdc

```

**Comment by LimWChing** [comment]
Sorry, silly me, I ended up on the page of the script in the beginning and I have just realized these scripts were all under gdc. I managed to get the script working now. Thank you!

**Comment by mathii** [comment]
Ok! sorry for the confusion and glad that you got it to work. Let me know if you have any other issues!

**Comment by Marvin02860** [comment]
Hello,
Is there a chance you could explain how you fixed your issue? 
I am no expert at all, but I got the exact same error message as you, and I don't understand what it means.
Thanks for any help :)
Marvin

**Comment by mathii** [comment]
You need to clone the whole idc project, not just this script.

**Comment by Marvin02860** [comment]
Thank you for your help,
now it is working :)
