### ISSUE TITLE
eigenstrat2vcf.py error

### ISSUE THREAD

**Issue by DcornishUCL** [mathii/gdc#4]
Hi,

I am trying to use your script eigenstrat2vcf.py however I am receiving the error:

Traceback (most recent call last):
  File "/bin/mathii_gdc/gdc/eigenstrat2vcf.py", line 67, in <module>
    main(options)
  File "/bin/mathii_gdc/gdc/eigenstrat2vcf.py", line 56, in main
    for i,d in enumerate(data):
TypeError: iter() returned non-iterator of type 'unpacked_data'

And I am using the commands:

`python3 -u /bin/mathii_gdc/gdc/eigenstrat2vcf.py -r v44.3_HO_public -i v44.3_HO_public.ind -p v44.3_HO_public_populations -s v44.3_HO_public.snp`

I wondered if maybe I am using the incorrect version of Python (3.8.6) and the script is written for an earlier version or perhaps I am using the wrong syntax? I tried with python 2.7.12 but that failed too. Any help to correct this matter would be much appreciated. 

Best wishes, 

Dean

**Comment by mathii** [comment]
Yes, sorry you definitely need python 2. Are you getting the same error with python 2.7?

**Comment by DcornishUCL** [comment]
Hi, actually I get the header of the VCF written to standard output but nothing else. I wondered if this was because one of my file is the wrong format.

##fileformat=VCFv4.0
##source=eigenstrat2vcf.py
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL

Example lines ind file:

MAL-005 M Malawi_Yao
MAL-009 M Malawi_Yao
MAL-011 M Malawi_Chewa

Example lines from population file:

Malawi_Yao
Malawi_Yao
Malawi_Chewa

Example lines from SNP file:

        rs3094315     1        0.020130          752566 G A
           rs7419119     1        0.022518          842013 T G
          rs13302957     1        0.024116          891021 G A

Example lines from eigenstrat file:

1211002212121 ....

**Comment by mathii** [comment]
Yes. Ok, so the -i option should be a list of individual IDs that you want to include (not the .ind file) and the -s option should be a list of snp IDs that you want to include (not the snp file). Your population file is correct. The script asssumes that the .geno, .ind and .snp files all have the same root (which you specified with -r). Assuming that you want to include all individuals (in the specified populations) and all snps, then you don't need the -i and -s options. 

So I think that: 

`python2 /bin/mathii_gdc/gdc/eigenstrat2vcf.py -r v44.3_HO_public -p v44.3_HO_public_populations 
`

should do what you want. If you want to further restrict the individuals or snps in your output then you could include the -I or -s options. These options are not heavily tested so please let me know if you see something weird in the output.
